-- public.datacosupplychaindataset definition

-- Drop table

-- DROP TABLE public.datacosupplychaindataset;
--Imported with Dbeaver

CREATE TABLE public.datacosupplychaindataset (
	"Type" varchar(50) NULL,
	"Days for shipping (real)" int4 NULL,
	"Days for shipment (scheduled)" int4 NULL,
	"Benefit per order" float4 NULL,
	"Sales per customer" float4 NULL,
	"Delivery Status" varchar(50) NULL,
	"Late_delivery_risk" int4 NULL,
	"Category Id" int4 NULL,
	"Category Name" varchar(50) NULL,
	"Customer City" varchar(50) NULL,
	"Customer Country" varchar(50) NULL,
	"Customer Email" varchar(50) NULL,
	"Customer Fname" varchar(50) NULL,
	"Customer Id" int4 NULL,
	"Customer Lname" varchar(50) NULL,
	"Customer Password" varchar(50) NULL,
	"Customer Segment" varchar(50) NULL,
	"Customer State" varchar(50) NULL,
	"Customer Street" varchar(50) NULL,
	"Customer Zipcode" varchar(20) NULL,
	"Department Id" varchar(50) NULL,
	"Department Name" varchar(50) NULL,
	"Latitude" float4 NULL,
	"Longitude" float4 NULL,
	"Market" varchar(50) NULL,
	"Order City" varchar(50) NULL,
	"Order Country" varchar(50) NULL,
	"Order Customer Id" int4 NULL,
	"order date (DateOrders)" varchar(50) NULL,
	"Order Id" int4 NULL,
	"Order Item Cardprod Id" int4 NULL,
	"Order Item Discount" float4 NULL,
	"Order Item Discount Rate" float4 NULL,
	"Order Item Id" int4 NULL,
	"Order Item Product Price" float4 NULL,
	"Order Item Profit Ratio" float4 NULL,
	"Order Item Quantity" int4 NULL,
	"Sales" float4 NULL,
	"Order Item Total" float4 NULL,
	"Order Profit Per Order" float4 NULL,
	"Order Region" varchar(50) NULL,
	"Order State" varchar(50) NULL,
	"Order Status" varchar(50) NULL,
	"Order Zipcode" int4 NULL,
	"Product Card Id" int4 NULL,
	"Product Category Id" int4 NULL,
	"Product Description" varchar(50) NULL,
	"Product Image" varchar(128) NULL,
	"Product Name" varchar(50) NULL,
	"Product Price" float4 NULL,
	"Product Status" int4 NULL,
	"shipping date (DateOrders)" varchar(50) NULL,
	"Shipping Mode" varchar(50) NULL
);